/**
 * GROOVY_WORKFLOW_CELLPOSE_WITH_LABEL_EXPORT.groovy
 *
 * PURPOSE (biologist-friendly)
 *   One-click, end-to-end TrackMate + Cellpose workflow that:
 *   (1) segments cells with Cellpose via TrackMate,
 *   (2) links detections into tracks,
 *   (3) exports tracks CSV and TrackMate XML,
 *   (4) captures the exact mask images generated by Cellpose in /tmp,
 *   (5) converts those mask images into a label TIFF stack.
 *
 * IMPORTANT LABEL NOTE
 *   The label TIFF is derived EXACTLY from the *_cp_masks.png files that Cellpose writes.
 *   This preserves Cellpose mask pixel values as saved by Cellpose output files.
 *
 * REQUIREMENTS
 *   - Fiji/ImageJ with TrackMate and TrackMate-Cellpose installed.
 *   - Cellpose reachable through the micromamba shim at
 *       /usr/local/opt/micromamba/bin/micromamba run -n base cellpose --version
 *     (the shim re-routes -n base → the real cellpose env). Verify with the
 *     command above before running this script.
 *
 * INPUT
 *   - Active image in Fiji (preferred), OR set imageName to a specific open window title.
 *
 * OUTPUT FILES
 *   - CSV track table:
 *       /app/data/projects/trackmate_cellpose_project/data/tracks_cellpose.csv
 *   - TrackMate XML session:
 *       /app/data/projects/trackmate_cellpose_project/data/session_cellpose.xml
 *   - Copied Cellpose temp exports (mask/reference files):
 *       /app/data/projects/trackmate_cellpose_project/processed_images/cellpose_temp_exports/
 *   - Label TIFF stack made from copied masks:
 *       /app/data/projects/trackmate_cellpose_project/processed_images/cellpose_labels_exact_from_masks.tif
 *
 * CORE PARAMETERS (edit below)
 *   - cellposeModel: default "cyto3"; common choices: "cyto3", "nuclei", "cyto2", "cyto"
 *   - targetChannel/optionalChannel, cellDiameter, linkingDist, gapClosingDist, maxFrameGap
 *
 * TROUBLESHOOTING
 *   - If TrackMate process fails, inspect Fiji log for detectorSettings and backend preflight lines.
 *   - If no /tmp/TrackMate-cellpose_* folder is found, Cellpose likely failed before writing outputs.
 *   - If no *_cp_masks files are found, check model/channel settings and inspect temp folder listing in log.
 */

import fiji.plugin.trackmate.Model
import fiji.plugin.trackmate.Settings
import fiji.plugin.trackmate.TrackMate
import fiji.plugin.trackmate.Logger
import fiji.plugin.trackmate.SpotCollection
import fiji.plugin.trackmate.cellpose.CellposeDetectorFactory
import fiji.plugin.trackmate.features.FeatureFilter
// NOTE: tracker factory is loaded via reflection (Pitfall C5) — no hardcoded import.
import fiji.plugin.trackmate.io.TmXmlWriter
import ij.IJ
import ij.ImagePlus
import ij.WindowManager
import ij.ImageStack
import ij.process.ImageProcessor
import ij.process.ShortProcessor
import java.io.File
import java.io.FileWriter
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.util.regex.Pattern

// ── PARAMETERS ───────────────────────────────────────────────────────────────
// targetChannel/optionalChannel use the **Cellpose 0-based convention**:
//   0 = grayscale, 1/2/3 = R/G/B. NOT the 1-based ImageJ channel index used by
//   the LoG/StarDist detectors elsewhere in TrackMate.
def imageName          = ''
def targetChannel      = 0
def optionalChannel    = 0
def cellDiameter       = 30.0d
def cellposeModel      = 'cyto3'
def customModelPath    = ''
def useGpu             = false
def simplifyContours   = true

def linkingDist         = 40.0d
def gapClosingDist     = 40.0d
def maxFrameGap        = 2
def minTrackLength     = 3

final String outputDirPath      = '/app/data/projects/trackmate_cellpose_project/data/'
final String csvPath            = '/app/data/projects/trackmate_cellpose_project/data/tracks_cellpose.csv'
final String xmlPath            = '/app/data/projects/trackmate_cellpose_project/data/session_cellpose.xml'
final String tempRootPath       = '/tmp'
final String tempPrefix         = 'TrackMate-cellpose_'
final String exportDirPath      = '/app/data/projects/trackmate_cellpose_project/processed_images/cellpose_temp_exports/'
final String outputLabelTiffPath= '/app/data/projects/trackmate_cellpose_project/processed_images/cellpose_labels_exact_from_masks.tif'

boolean overallSuccess = false
boolean workflowSuccess = false

try {
    ImagePlus imp = null
    if (imageName != null && !imageName.isEmpty()) {
        imp = WindowManager.getImage(imageName)
        if (imp == null) IJ.log("[WARN] Image '${imageName}' not found. Falling back to active image.")
    }
    if (imp == null) {
        try {
            imp = IJ.getImage()
        } catch (Exception ignored) {
            imp = null
        }
    }
    if (imp == null) {
        IJ.log('[ERROR] No open image available. Aborting.')
        println('FINAL STATUS: FAILURE - No image open.')
        return
    }

    def imp2 = imp.duplicate()

    IJ.log('[INFO] Processing image: ' + imp.getTitle())
    IJ.log('[INFO] Dimensions: ' + imp.getWidth() + 'x' + imp.getHeight() + ', C=' + imp.getNChannels() + ', Z=' + imp.getNSlices() + ', T=' + imp.getNFrames())

    if (imp.getNFrames() == 1 && imp.getNSlices() > 1) {
        IJ.log('[WARN] Detected Z>1 and T=1; reclassifying slices as frames for tracking.')
        imp.setDimensions(imp.getNChannels(), 1, imp.getNSlices())
    }

    long startTs = System.currentTimeMillis()

    def model = new Model()
    model.setLogger(Logger.IJ_LOGGER)
    def settings = new Settings(imp)

    // Verify the micromamba shim can reach cellpose before we hand off to TrackMate.
    try {
        String[] cmd = ['/usr/local/opt/micromamba/bin/micromamba', 'run', '-n', 'base', 'cellpose', '--version'] as String[]
        IJ.log('[INFO] Cellpose preflight: ' + cmd.join(' '))
        def proc = new ProcessBuilder(cmd).redirectErrorStream(true).start()
        def outText = proc.inputStream.getText('UTF-8')
        int exitCode = proc.waitFor()
        if (exitCode != 0) {
            IJ.log('[WARN] Cellpose preflight failed (exit=' + exitCode + '). Output: ' + (outText == null ? '' : outText.trim()))
        } else {
            IJ.log('[INFO] Cellpose version: ' + (outText == null ? '' : outText.trim()))
        }
    } catch (Exception e) {
        IJ.log('[WARN] Cellpose preflight exception: ' + e.getMessage())
    }

    settings.detectorFactory = new CellposeDetectorFactory()
    settings.detectorSettings = [
        'CONDA_ENV'                : 'base',
        'CELLPOSE_MODEL'           : cellposeModel,
        'CELLPOSE_MODEL_FILEPATH'  : customModelPath,
        'PRETRAINED_OR_CUSTOM'     : (customModelPath != null && !customModelPath.isEmpty()) ? 'CUSTOM_MODEL' : 'CELLPOSE_MODEL',
        'TARGET_CHANNEL'           : String.valueOf(targetChannel),
        'OPTIONAL_CHANNEL_2'       : String.valueOf(optionalChannel),
        'CELL_DIAMETER'            : (double) cellDiameter,
        'USE_GPU'                  : useGpu,
        'SIMPLIFY_CONTOURS'        : simplifyContours,
    ]

    settings.initialSpotFilterValue = 0.0d
    settings.addAllAnalyzers()

    // C5 — reflection-based tracker factory loader (handles sparselap→jaqaman rename).
    String[] trackerCandidates = [
        'fiji.plugin.trackmate.tracking.jaqaman.SparseLAPTrackerFactory',
        'fiji.plugin.trackmate.tracking.jaqaman.SimpleSparseLAPTrackerFactory',
        'fiji.plugin.trackmate.tracking.sparselap.SparseLAPTrackerFactory',
    ]
    def trackerFactory = null
    for (String cn : trackerCandidates) {
        try {
            trackerFactory = Class.forName(cn).getDeclaredConstructor().newInstance()
            IJ.log('[INFO] Tracker factory: ' + cn); break
        } catch (Throwable ignored) { }
    }
    if (trackerFactory == null) {
        IJ.log('[ERROR] No SparseLAP/SimpleSparseLAP factory found; aborting.')
        println('FINAL STATUS: FAILURE - No tracker factory.'); return
    }
    settings.trackerFactory  = trackerFactory
    settings.trackerSettings = trackerFactory.getDefaultSettings()
    settings.trackerSettings['LINKING_MAX_DISTANCE']     = (double) linkingDist
    settings.trackerSettings['GAP_CLOSING_MAX_DISTANCE'] = (double) gapClosingDist
    settings.trackerSettings['MAX_FRAME_GAP']            = (Integer) maxFrameGap
    settings.addTrackFilter(new FeatureFilter('NUMBER_SPOTS', (double) minTrackLength, true))

    def trackmate = new TrackMate(model, settings)
    IJ.log('[INFO] Checking TrackMate input...')
    if (!trackmate.checkInput()) {
        IJ.log('[ERROR] checkInput failed: ' + trackmate.getErrorMessage())
    } else {
        IJ.log('[INFO] Running TrackMate process()...')
        if (!trackmate.process()) {
            IJ.log('[ERROR] process() failed: ' + trackmate.getErrorMessage())
        } else {
            workflowSuccess = true
            IJ.log('[INFO] TrackMate process completed.')
            IJ.log('[INFO] Total spots: ' + model.getSpots().getNSpots(true))
            IJ.log('[INFO] Total tracks (filtered): ' + model.getTrackModel().nTracks(true))
            IJ.log('[INFO] Total tracks (all): ' + model.getTrackModel().nTracks(false))
        }
    }

    new File(outputDirPath).mkdirs()

    // CSV export
    try {
        File csvFile = new File(csvPath)
        FileWriter writer = new FileWriter(csvFile)
        try {
            writer.write('TRACK_ID,FRAME,POSITION_X,POSITION_Y,POSITION_Z,RADIUS,QUALITY,MEAN_INTENSITY\n')
            int rows = 0
            boolean detectionsOnlyFallbackUsed = false
            if (workflowSuccess) {
                int nTracksAll = model.getTrackModel().nTracks(false)
                if (nTracksAll == 0) {
                    detectionsOnlyFallbackUsed = true
                    SpotCollection allSpots = model.getSpots()
                    for (int frame = 0; frame < imp.getNFrames(); frame++) {
                        def spotsAtFrame = allSpots.iterable(frame, true)
                        for (def spot in spotsAtFrame) {
                            double x = spot.getFeature('POSITION_X')
                            double y = spot.getFeature('POSITION_Y')
                            double z = (spot.getFeature('POSITION_Z') == null) ? 0.0d : spot.getFeature('POSITION_Z')
                            double r = spot.getFeature('RADIUS')
                            double q = spot.getFeature('QUALITY')
                            double mi = (spot.getFeature('MEAN_INTENSITY') == null) ? 0.0d : spot.getFeature('MEAN_INTENSITY')
                            writer.write("-1,${frame},${x},${y},${z},${r},${q},${mi}\n")
                            rows++
                        }
                    }
                } else {
                    for (def trackId in model.getTrackModel().trackIDs(true)) {
                        def spots = new ArrayList(model.getTrackModel().trackSpots(trackId))
                        spots.sort { a, b -> a.getFeature('FRAME') <=> b.getFeature('FRAME') }
                        for (def spot in spots) {
                            int frame = spot.getFeature('FRAME').intValue()
                            double x = spot.getFeature('POSITION_X')
                            double y = spot.getFeature('POSITION_Y')
                            double z = (spot.getFeature('POSITION_Z') == null) ? 0.0d : spot.getFeature('POSITION_Z')
                            double r = spot.getFeature('RADIUS')
                            double q = spot.getFeature('QUALITY')
                            double mi = (spot.getFeature('MEAN_INTENSITY') == null) ? 0.0d : spot.getFeature('MEAN_INTENSITY')
                            writer.write("${trackId},${frame},${x},${y},${z},${r},${q},${mi}\n")
                            rows++
                        }
                    }
                }
            }
            IJ.log('[INFO] CSV written: ' + csvFile.getAbsolutePath() + ' (rows=' + rows + ')')
            IJ.log('[INFO] CSV detections-only fallback used: ' + detectionsOnlyFallbackUsed)
        } finally {
            try { writer.flush() } catch (Exception ignored) {}
            try { writer.close() } catch (Exception ignored) {}
        }
    } catch (Exception e) {
        IJ.log('[ERROR] CSV export failed: ' + e.getMessage())
    }

    // XML export
    try {
        File xmlFile = new File(xmlPath)
        def xmlWriter = new TmXmlWriter(xmlFile, Logger.IJ_LOGGER)
        xmlWriter.appendModel(model)
        xmlWriter.appendSettings(settings)
        xmlWriter.writeToFile()
        IJ.log('[INFO] XML written: ' + xmlFile.getAbsolutePath())
    } catch (Exception e) {
        IJ.log('[ERROR] XML export failed: ' + e.getMessage())
    }

    // Find newest temp directory generated after run start when possible
    File tempRoot = new File(tempRootPath)
    if (!tempRoot.exists() || !tempRoot.isDirectory()) {
        IJ.log('[ERROR] Temp root unavailable: ' + tempRootPath)
    } else {
        File[] candidates = tempRoot.listFiles()
        if (candidates == null) candidates = new File[0]
        List<File> cpDirs = candidates.findAll { File f -> f != null && f.isDirectory() && f.getName().startsWith(tempPrefix) }

        if (cpDirs.isEmpty()) {
            IJ.log('[ERROR] No temp folders found matching: ' + tempRootPath + '/' + tempPrefix + '*')
        } else {
            List<File> recent = cpDirs.findAll { it.lastModified() >= (startTs - 5000L) }
            List<File> pool = recent.isEmpty() ? cpDirs : recent
            pool.sort { a, b -> a.lastModified() <=> b.lastModified() }
            File selectedTempDir = pool.last()
            IJ.log('[INFO] Selected temp folder: ' + selectedTempDir.getAbsolutePath())

            File exportDir = new File(exportDirPath)
            if (!exportDir.exists()) exportDir.mkdirs()
            if (!exportDir.exists() || !exportDir.isDirectory()) {
                IJ.log('[ERROR] Could not create export directory: ' + exportDirPath)
            } else {
                File[] tempFilesArr = selectedTempDir.listFiles()
                if (tempFilesArr == null) tempFilesArr = new File[0]
                List<File> tempFiles = tempFilesArr.toList()

                Pattern p1 = Pattern.compile('.*_cp_masks\\.(png|tif|tiff)$', Pattern.CASE_INSENSITIVE)
                Pattern p2 = Pattern.compile('.*masks.*\\.(png|tif|tiff)$', Pattern.CASE_INSENSITIVE)
                Pattern p3 = Pattern.compile('.*_cp\\.png$', Pattern.CASE_INSENSITIVE)

                List<File> filesToCopy = tempFiles.findAll { File f ->
                    if (f == null || !f.isFile()) return false
                    String n = f.getName()
                    return p1.matcher(n).matches() || p2.matcher(n).matches() || p3.matcher(n).matches()
                }

                IJ.log('[INFO] Files selected for copy: ' + filesToCopy.size())
                List<File> copiedFiles = []

                for (File src : filesToCopy) {
                    try {
                        File dst = new File(exportDir, src.getName())
                        Files.copy(src.toPath(), dst.toPath(), StandardCopyOption.REPLACE_EXISTING)
                        copiedFiles << dst
                        IJ.log('[INFO] Copied: ' + src.getName() + ' -> ' + dst.getAbsolutePath())
                    } catch (Exception ce) {
                        IJ.log('[WARN] Copy failed for ' + src.getAbsolutePath() + ': ' + ce.getMessage())
                    }
                }

                List<File> maskCandidates = copiedFiles.findAll { File f ->
                    String n = f.getName().toLowerCase()
                    return n.matches('.*_cp_masks\\.(png|tif|tiff)$')
                }
                if (maskCandidates.isEmpty()) {
                    maskCandidates = copiedFiles.findAll { File f ->
                        String n = f.getName().toLowerCase()
                        return n.matches('.*masks.*\\.(png|tif|tiff)$')
                    }
                }

                if (maskCandidates.isEmpty()) {
                    IJ.log('[ERROR] No mask files found after copy.')
                } else {
                    maskCandidates.sort { File a, File b ->
                        int ia = extractLeadingIndex(a.getName())
                        int ib = extractLeadingIndex(b.getName())
                        if (ia != ib) return ia <=> ib
                        return a.getName() <=> b.getName()
                    }

                    ImageStack outStack = null
                    int outW = -1
                    int outH = -1

                    for (File mf : maskCandidates) {
                        try {
                            ImagePlus mImp = IJ.openImage(mf.getAbsolutePath())
                            if (mImp == null) {
                                IJ.log('[WARN] Could not open mask image: ' + mf.getAbsolutePath())
                                continue
                            }

                            ImageProcessor ip = mImp.getProcessor()
                            if (ip == null) {
                                IJ.log('[WARN] No processor in mask image: ' + mf.getAbsolutePath())
                                mImp.close()
                                continue
                            }

                            if (mImp.getBitDepth() == 24 || mImp.getNChannels() > 1) {
                                IJ.run(mImp, '8-bit', '')
                                ip = mImp.getProcessor()
                            }

                            int w = ip.getWidth()
                            int h = ip.getHeight()
                            short[] pix16 = new short[w * h]

                            for (int y = 0; y < h; y++) {
                                int row = y * w
                                for (int x = 0; x < w; x++) {
                                    int v = (int)Math.round(ip.getf(x, y))
                                    if (v < 0) v = 0
                                    if (v > 65535) v = 65535
                                    pix16[row + x] = (short)(v & 0xFFFF)
                                }
                            }

                            ShortProcessor sp = new ShortProcessor(w, h, pix16, null)
                            if (outStack == null) {
                                outW = w
                                outH = h
                                outStack = new ImageStack(w, h)
                            }

                            if (w != outW || h != outH) {
                                IJ.log('[WARN] Size mismatch, skipping: ' + mf.getName())
                                mImp.close()
                                continue
                            }

                            outStack.addSlice(mf.getName(), sp)
                            mImp.close()
                        } catch (Exception me) {
                            IJ.log('[WARN] Failed converting mask ' + mf.getAbsolutePath() + ': ' + me.getMessage())
                        }
                    }

                    if (outStack == null || outStack.getSize() == 0) {
                        IJ.log('[ERROR] No valid mask slices converted; label TIFF not saved.')
                    } else {
                        try {
                            ImagePlus outImp = new ImagePlus('cellpose_labels_exact_from_masks', outStack)
                            File outFile = new File(outputLabelTiffPath)
                            if (outFile.getParentFile() != null && !outFile.getParentFile().exists()) outFile.getParentFile().mkdirs()
                            IJ.saveAsTiff(outImp, outFile.getAbsolutePath())
                            outImp.close()

                            File verify = new File(outFile.getAbsolutePath())
                            if (verify.exists() && verify.length() > 0) {
                                IJ.log('[INFO] Label TIFF saved: ' + verify.getAbsolutePath() + ' (bytes=' + verify.length() + ')')
                                overallSuccess = workflowSuccess
                            } else {
                                IJ.log('[ERROR] Label TIFF save verification failed: ' + outFile.getAbsolutePath())
                            }
                        } catch (Exception se) {
                            IJ.log('[ERROR] Failed writing label TIFF: ' + se.getMessage())
                        }
                    }
                }
            }
        }
    }

    imp2.show()

} catch (Exception e) {
    IJ.log('[ERROR] Unhandled exception: ' + e.getMessage())
    e.printStackTrace()
}

if (overallSuccess) {
    println('FINAL STATUS: SUCCESS')
} else {
    println('FINAL STATUS: FAILURE')
}

int extractLeadingIndex(String name) {
    def m = (name =~ /^(\d+)_/)
    if (m.find()) {
        try {
            return Integer.parseInt(m.group(1))
        } catch (Exception ignored) {
            return Integer.MAX_VALUE
        }
    }
    return Integer.MAX_VALUE
}
