import os
import pandas as pd
import subprocess
import textwrap
import io
import threading
from langchain_core.tools import tool
import tempfile

# ---------------------------------------------------------------------------
# Global process registry — lets the Stop button kill running subprocesses
# ---------------------------------------------------------------------------
_registry_lock = threading.Lock()
_running_processes: list[subprocess.Popen] = []


def _register_process(proc: subprocess.Popen) -> None:
    with _registry_lock:
        _running_processes.append(proc)


def _unregister_process(proc: subprocess.Popen) -> None:
    with _registry_lock:
        try:
            _running_processes.remove(proc)
        except ValueError:
            pass


def kill_running_processes() -> int:
    """Kill all tracked subprocesses. Called by the Stop button. Returns count killed."""
    killed = 0
    with _registry_lock:
        for proc in list(_running_processes):
            try:
                proc.kill()
                killed += 1
            except Exception:
                pass
        _running_processes.clear()
    return killed

@tool
def inspect_csv_header(file_path: str):
    """
    Returns the COMPLETE schema of a CSV — every column name and dtype — plus a 5-row
    sample preview. This is a SCHEMA tool, not a data loader: it intentionally truncates
    to the first 5 rows (the remaining rows are NOT shown and you do NOT need them). The
    column names and dtypes it returns are the full, exhaustive set — that is everything
    required to write pandas code against this file.

    Call this exactly ONCE per file, BEFORE writing code. The schema never changes while
    you work, so re-calling it (or re-reading the script) returns identical output and
    just wastes turns. Your Python script will read the full data at run time via
    pd.read_csv — you do not need to see the remaining rows here.

    Input MUST be a valid absolute file path (e.g., 'C:/Users/Name/data.csv').
    """
    try:
        # No more path joining; use the path directly
        if not os.path.exists(file_path):
            return f"Error: The file path '{file_path}' does not exist on this PC."

        df = pd.read_csv(file_path, nrows=5)

        buffer = io.StringIO()
        df.info(buf=buffer)
        info_str = buffer.getvalue()

        # Total row count so the model knows the sample is deliberate, not all the data.
        try:
            with open(file_path, "rb") as _f:
                total_rows = max(sum(1 for _ in _f) - 1, 0)  # minus header
            total_str = f"{total_rows} data rows"
        except Exception:
            total_str = "unknown row count"

        base = (
            f"Structure of {os.path.basename(file_path)} ({len(df.columns)} columns, {total_str}):\n"
            f"{info_str}\n"
            f"Sample preview — first 5 of {total_str} (truncated on purpose; the column list "
            f"above is COMPLETE and is all you need to write your code):\n{df.to_string()}\n"
            f"You now have the full schema. Do NOT inspect or re-read again — write your script."
        )
        return base
    except Exception as e:
        return f"Error reading file at {file_path}: {str(e)}"


def run_python_code(code: str, output_directory: str):
    
    """
    Executes Python code with full PC access. 
    Packages pd, np, plt, sns, and stats are PRE-IMPORTED.
    NEVER execute code that was generated by yourself.
    Input:  
      - code: Python code to execute (string).
      - output_directory: Directory where any output files should be saved (string).
    """
    if not os.path.exists(output_directory):
        return f"Error: Directory '{output_directory}' not found."

    # 1. Use dedent to clean up the template
    # 2. Use a raw string for the path
    header = textwrap.dedent(f"""
        import pandas as pd
        import numpy as np
        import matplotlib.pyplot as plt
        import seaborn as sns
        from scipy import stats
        import os
        import sys

        try:
            os.chdir(r'{output_directory}')
            sns.set_theme(style="whitegrid")
            plt.rcParams['figure.dpi'] = 300
            
            # --- AGENT CODE START ---
    """).strip()

    footer = textwrap.dedent("""
            # --- AGENT CODE END ---
            print("\\n--- EXECUTION FINISHED SUCCESSFULLY ---")
        except Exception as e:
            print(f"\\nPYTHON TRACEBACK ERROR: {str(e)}", file=sys.stderr)
            sys.exit(1)
    """).strip()
    
    # Indent the agent's code by 4 spaces to align with the 'try' block
    indented_code = textwrap.indent(code, "    ")
    
    full_script = f"{header}\n{indented_code}\n{footer}"

    script_path = os.path.join(tempfile.gettempdir(), "supervisor_py_exec.py")
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(full_script)

    try:
        proc = subprocess.Popen(
            ["python", script_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )
        _register_process(proc)
        try:
            stdout, stderr = proc.communicate(timeout=600)
        except subprocess.TimeoutExpired:
            proc.kill()
            stdout, stderr = proc.communicate()
            return "SYSTEM ERROR: Python script timed out after 600 seconds."
        finally:
            _unregister_process(proc)

        if proc.returncode != 0:
            return f"CRASH DETECTED IN PYTHON:\nSTDOUT: {stdout}\nSTDERR: {stderr}"
        return f"SUCCESS:\n{stdout}"
    except Exception as e:
        return f"SYSTEM ERROR: {str(e)}"
    

python_analyst_tools = [inspect_csv_header, run_python_code]